export class DotpayUrlcEntity {
    id: string
    operation_number: string
    operation_type: string
    operation_status: string
    operation_amount: string
    operation_currency: string
    operation_withdrawal_amount: string
    operation_commission_amount: string
    is_completed: string
    operation_original_amount: string
    operation_original_currency: string
    operation_datetime: string
    operation_related_number: string
    control: string
    description: string
    email: string
    p_info: string
    p_email: string
    credit_card_issuer_identification_number: number
    credit_card_masked_number: string
    credit_card_expiration_year: string
    credit_card_expiration_month: string
    credit_card_brand_codename: string
    credit_card_brand_code: string
    credit_card_unique_identifier: string
    credit_card_id: string
    channel: string
    channel_country: string
    geoip_country: string
    payer_bank_account_name: string
    payer_bank_account: string
    payer_transfer_title: string
    blik_voucher_pin: string
    blik_voucher_amount: string
    blik_voucher_amount_used: string
    channel_reference_id: string
    operation_seller_code: string
}
